### PR TITLE
LATTICE-2405 change property tags from multimap to map

### PR DESCRIPTION
**Pull request by you-leee**

### CODE REVIEW

**Review by pckeyes — APPROVED** [review]

**Comment by katherinebernstein** [comment]
I'm a little confused -- what's the reason for moving away from multimaps here?

**Comment by you-leee** [comment]
> I'm a little confused -- what's the reason for moving away from multimaps here?

Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)

**Comment by katherinebernstein** [comment]
> > I'm a little confused -- what's the reason for moving away from multimaps here?
> 
> Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)

Yeah I think we did, I just didn't remember *why* we're trying to move away from multimaps (other than the DataApi.updateEntitiesInEntitySet case).

What's the multimap serdes error? /is there a reason we're moving away from multimaps other than because of that error?

**Comment by you-leee** [comment]
> > > I'm a little confused -- what's the reason for moving away from multimaps here?
> > 
> > 
> > Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)
> 
> Yeah I think we did, I just didn't remember _why_ we're trying to move away from multimaps (other than the DataApi.updateEntitiesInEntitySet case).
> 
> What's the multimap serdes error? /is there a reason we're moving away from multimaps other than because of that error?

It was the one, when it returned `{"empty":false}` for property tags when you were trying to retrieve an entity type. 
In my opinion, it can be confusing to use two different kind of "maps", bc there are these subtle differences which can be easily overlooked, like the serialization of multimaps will just ignore empty valued keys, which can lead to errors/compromised data.

**Comment by katherinebernstein** [comment]
> > > > I'm a little confused -- what's the reason for moving away from multimaps here?
> > > 
> > > 
> > > Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)
> > 
> > 
> > Yeah I think we did, I just didn't remember _why_ we're trying to move away from multimaps (other than the DataApi.updateEntitiesInEntitySet case).
> > What's the multimap serdes error? /is there a reason we're moving away from multimaps other than because of that error?
> 
> It was the one, when it returned `{"empty":false}` for property tags when you were trying to retrieve an entity.
> In my opinion, it can be confusing to use two different kind of "maps", bc there are these subtle differences which can be easily overlooked, like the serialization of multimaps will just ignore empty valued keys, which can lead to errors/compromised data.

Oh I don't think that's a multimap-specific error -- we've seen that on serializing regular HashMaps/POJOs too (like on loading the EDM).

That's true, but I think sometimes the specific behavior of mutlimaps can be useful. With these property tags, it seems like most of the multimap functionality is basically being reimplemented on regular maps, so to me, it seems cleaner/more maintainable to just leave the multimaps.

I'm open to changing them all to regular maps! I just think it's worth discussing.

**Comment by you-leee** [comment]
> > > > > I'm a little confused -- what's the reason for moving away from multimaps here?
> > > > 
> > > > 
> > > > Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)
> > > 
> > > 
> > > Yeah I think we did, I just didn't remember _why_ we're trying to move away from multimaps (other than the DataApi.updateEntitiesInEntitySet case).
> > > What's the multimap serdes error? /is there a reason we're moving away from multimaps other than because of that error?
> > 
> > 
> > It was the one, when it returned `{"empty":false}` for property tags when you were trying to retrieve an entity.
> > In my opinion, it can be confusing to use two different kind of "maps", bc there are these subtle differences which can be easily overlooked, like the serialization of multimaps will just ignore empty valued keys, which can lead to errors/compromised data.
> 
> Oh I don't think that's a multimap-specific error -- we've seen that on serializing regular HashMaps/POJOs too (like on loading the EDM).
> 
> That's true, but I think sometimes the specific behavior of mutlimaps can be useful. With these property tags, it seems like most of the multimap functionality is basically being reimplemented on regular maps, so to me, it seems cleaner/more maintainable to just leave the multimaps.
> 
> I'm open to changing them all to regular maps! I just think it's worth discussing.

I think in this case if for some reason - an api is generating empty tags, someone forgot to add tags to a property type manually - values are left empty, we shouldn't hide the error by removing empty valued entries on serialization of property tags, but rather check them.

**Comment by katherinebernstein** [comment]
> > > > > > I'm a little confused -- what's the reason for moving away from multimaps here?
> > > > > 
> > > > > 
> > > > > Well, for one, that we won't have that weird multimap serdes error that sometimes mysteriously appears plus as far as I know, we want to move away from multimaps (we had this discussion also in another PR I think)
> > > > 
> > > > 
> > > > Yeah I think we did, I just didn't remember _why_ we're trying to move away from multimaps (other than the DataApi.updateEntitiesInEntitySet case).
> > > > What's the multimap serdes error? /is there a reason we're moving away from multimaps other than because of that error?
> > > 
> > > 
> > > It was the one, when it returned `{"empty":false}` for property tags when you were trying to retrieve an entity.
> > > In my opinion, it can be confusing to use two different kind of "maps", bc there are these subtle differences which can be easily overlooked, like the serialization of multimaps will just ignore empty valued keys, which can lead to errors/compromised data.
> > 
> > 
> > Oh I don't think that's a multimap-specific error -- we've seen that on serializing regular HashMaps/POJOs too (like on loading the EDM).
> > That's true, but I think sometimes the specific behavior of mutlimaps can be useful. With these property tags, it seems like most of the multimap functionality is basically being reimplemented on regular maps, so to me, it seems cleaner/more maintainable to just leave the multimaps.
> > I'm open to changing them all to regular maps! I just think it's worth discussing.
> 
> I think in this case if for some reason - an api is generating empty tags, someone forgot to add tags to a property type manually - values are left empty, we shouldn't hide the error by removing empty valued entries on serialization of property tags, but rather check them.

To me, it doesn't seem important enough (especially in this case since the EDM updates are managed entirely by us and not customers) to be worth reimplementing+maintaining all the multimap logic just so that we can throw that one exception in that one case. 

If that case is really important to handle in general, I'd prefer having an api take a `Map<Thing1, Set<Thing2>>` as input, validate it, and then convert to `SetMultimap<Thing1, Thing2>` to store and process from there on in.

Curious to hear the rest of the team's opinions though!

**Review by dbt — APPROVED** [review]

**Comment by dbt** [comment]
I generally prefer using Map<K, Set<V>> over SetMultimap<K, V> anywhere except in temporaries. They can be convenient when doing data transforms but don't return them that way.

I don't like using them as long term state, serializing them, or putting them in APIs anywhere. So I'm comfortable with this refactor.

(That said, this is exactly the kind of change that breaks doing live upgrades of conductor).

**Review by geekbeast — APPROVED** [review]

**Comment by geekbeast** [comment]
Also, I will add with kotlin built-in maps are superior to the multimap API for almost all purposes.

**Pull request merged**
